### ISSUE TITLE
Initialize repository with Life in Months app code

### ISSUE THREAD

**Issue by Mezee** [Mezee/life-in-months-app#1]
This issue tracks the implementation of the Life in Months app, which visualizes a human lifespan as a grid of months with notable achievements highlighted.

## Features
- Date picker for entering birth date
- Visual grid of 1,080 months (90 years)
- Blue circles for lived months
- Green circles for notable achievements
- Tooltips with achievement details
- Dark theme with modern styling
- Responsive design

**Comment by Mezee** [comment]
Continuing with the rest of the CSS styling for the component:

```css
.stat-label {
  font-size: 0.9rem;
  color: #b0b0b0;
}

.life-grid-container {
  margin-top: 30px;
}

.legend {
  display: flex;
  justify-content: center;
  gap: 30px;
  margin-bottom: 20px;
}

.legend-item {
  display: flex;
  align-items: center;
  gap: 10px;
}

.month-row {
  display: flex;
  justify-content: center;
  margin-bottom: 6px;
}

.month-circle {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background-color: #3a3a3c;
  margin: 0 3px;
  position: relative;
  transition: transform 0.2s;
}

.month-circle:hover {
  transform: scale(1.5);
  z-index: 10;
}

.month-circle.lived {
  background-color: #0a84ff;
}

.month-circle.achievement {
  background-color: #30d158;
  cursor: help;
}

.achievement-dot {
  position: absolute;
  width: 6px;
  height: 6px;
  background-color: #fff;
  border-radius: 50%;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.instructions {
  text-align: center;
  margin-top: 30px;
  color: #b0b0b0;
  font-size: 0.9rem;
}

/* For smaller screens */
@media (max-width: 768px) {
  .month-circle {
    width: 10px;
    height: 10px;
    margin: 0 2px;
  }
  
  .month-row {
    margin-bottom: 4px;
  }
  
  .stats-container {
    flex-direction: column;
    align-items: center;
    gap: 15px;
  }
  
  .stat-box {
    width: 80%;
    max-width: 200px;
  }
}
```

To use this component in a React application:

1. Create a file named `LifeInMonths.js` with the component code provided
2. Create a CSS file named `LifeInMonths.css` with the styles provided
3. Import the component into your main app:

```jsx
import React from 'react';
import LifeInMonths from './components/LifeInMonths';
import './App.css';

function App() {
  return (
    <div className="App">
      <LifeInMonths />
    </div>
  );
}

export default App;
```

The component is fully responsive and provides an interactive visualization of life in months, with special highlights for notable achievements.
